### ISSUE TITLE
SETUP_MFA not supported on ios & android sdk

### ISSUE THREAD

**Issue by vikkyios** [aws-amplify/amplify-swift#1045]
We are using native iOS & Android SDK, migrating user from old system to cognito.
Some users don't have phone number setup, its throwing exception. 

AuthError: Unexpected error occurred with message: nil: Error information not available.
Recovery suggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered at:
 Express/Pods/Amplify/Amplify/Categories/Auth/Error/AuthError.swift
function: recoverySuggestion
line: 79
  ▿ unknown : 2 elements
    - .0 : "nil: Error information not available."
    - .1 : nil

**Comment by lawmicha** [comment]
Hi @vikkyios, what do you mean by old system? how are you migrating to cognito? What steps do you take to migrate a user? 

Are you using any admin APIs to migrate the users? or using something in the AWS Cognito console?

Which API calls are you using from `Amplify.Auth` that is returning the `AuthError`? which APIs are working as expected?

**Comment by palpatim** [comment]
The issue is that there is a challenge coming back from Cognito (the above-mentioned `SETUP_MFA`) that is not being handled correctly in the native clients. Android has code that appears to handle it, but the code apparently has bugs with it. The iOS client does not handle this challenge at all. This feature is not currently on our road map.

The suggested workaround is to have customers impacted by this situation complete their first sign-in and MFA setup on the web. After, they will be able to login to the native client.

Please let us know if you have any further questions on this issue.

**Comment by harsh62** [comment]
Amplify added support for TOTP MFA in [2.16.0](https://github.com/aws-amplify/amplify-swift/releases/tag/2.16.0).
