### ISSUE TITLE
Auth User attributes does not support all of the standard user attributes that Android does

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-swift#1248]
**Describe the bug**
Amplify.Auth add user attributes has different cases from Android

See question here: https://github.com/aws-amplify/amplify-android/issues/787

Android response: https://github.com/aws-amplify/amplify-android/issues/787#issuecomment-685992257

iOS action item: https://github.com/aws-amplify/amplify-android/issues/787#issuecomment-849710290

> iOS should probably add those missing cases and make sure it is an additive change to the developer's perspective

Flutter issue: https://github.com/aws-amplify/amplify-flutter/issues/598

Flutter workaround: https://github.com/aws-amplify/amplify-flutter/issues/598#issuecomment-849715738

**Comment by royjit** [comment]
iOS auth plugin should have the standard attributes - https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims . This will be a breaking change for the customer since we are moving the new attributes from `unknown` type to the specific type. 

I am marking this as a feature for the 2.0.0 milestone for now.

**Comment by harsh62** [comment]
Amplify 2.0 has been released https://github.com/aws-amplify/amplify-swift/releases/tag/v2.0.0 that supports all the standard attributes https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims.
