### ISSUE TITLE
Server-side filtering of DataStore sync expressions

### ISSUE THREAD

**Issue by nfarrell36** [aws-amplify/amplify-swift#1635]
### Is your feature request related to a problem? Please describe.

DataStore, by default, pulls in as many model objects as possible (default is 10k) from the server to the client. This is a security concern for social apps where users have private information that should be hidden from other users. 

### Describe the solution you'd like

The solution I would like is for sync expressions to be filtered on the server so that the client doesn't receive any models that it is not supposed to have access to. 

### Describe alternatives you've considered

In order to not pull in all model objects, I have written custom sync expressions to only pull the models from DataStore that I am looking for. While that works, a member of the Discord chat informed me that the sync expressions pull all of the data it can from the server and then client-side filtering returns the models you are looking for - leaving the same security concern. 

### Is the feature request related to any of the existing Amplify categories?

DataStore

**Comment by alharris-at** [comment]
@nfarrell36 Subscriptions should be filtering out data that a user does not have access to.

Could you provide your GraphQL Schema and SyncExpression so we can verify? Documentation on how authorization rules work can be found here https://docs.amplify.aws/cli/graphql/authorization-rules/#per-user--owner-based-data-access

There are some known limitations, if you're attempting to provide a list of `owner`s or a list of owning `group`s then subscriptions will be disabled. This limitation is something we are looking to address this year.

**Comment by Rafiki81** [comment]
@alharris-at Hi, once Enhanced Subscription filters are available, it would be great to be able to use it with Amplify-Datastore (DataStoreSyncExpression) so the filtering on the subscriptions can be done at the server-side:

https://docs.aws.amazon.com/appsync/latest/devguide/aws-appsync-real-time-enhanced-filtering.html

Is there a way to pass the filtering parameter when defining the datastore sync expressions? We are having too much network traffic because the filtering is being made on the client-side (500 times more than it should be).
It's also causing some performance and stability issues on our mobile apps.
Is there another way to use this enhanced filtering that we are not aware of?

**Comment by alharris-at** [comment]
@Rafiki81 since that functionality launched at the beginning of April, we've been looking to integrate into Datastore sync expressions. Today the functionality for filtering is very limited in DataStore, but we are planning to add support for enhanced filtering in DataStore and via the `API` category of Amplify. If you are encountering issues in the immediate term however, you will likely need to either review your data model and look for ways to reduce the r/w rate of these subscribed tables, or if that's not feasible, you can [override resolvers](https://docs.amplify.aws/cli/graphql/override/) to add the subscription functionality, then leverage the [`API` subscriptions](https://docs.amplify.aws/lib/graphqlapi/subscribe-data/q/platform/ios/) instead of DataStore.

**Comment by caridavidson** [comment]
I'm also having this problem.  I don't think this is a P3 "feature request"  Security concerns, especially in an age of data privacy laws, should not be P3.   What you're saying is that anyone wwho knows that DataStore is pulling all the records can go to their browser console, mimic an API request, and browse all of the data from everyone else on the platform?

**Comment by thisisabhash** [comment]
@caridavidson you can create authorization rules on your data models to enforce authorization strategies and also restrict allowed operations. For reference: 
https://docs.amplify.aws/cli/graphql/authorization-rules/

**Comment by harsh62** [comment]
Hello @caridavidson,

​Thank you for reaching out to AWS regarding our documentation about the DataStore selective sync feature. Selective sync gives you the ability to apply additional filtering to the dataset which you are authorized to access, not the entire contents of the table in the data source.

​Authorization rules are defined on the schema with the @auth directive as stated above, and these rules are enforced in the AppSync service. There is no way for a client to circumvent these authorization rules by changing the filter expression in the request, because the filtering only gets applied to the data that client has access to. We have updated our [documentation](https://docs.amplify.aws/lib/datastore/sync/q/platform/ios/) to clarify this.

Here is an example of how selective sync works with existing authorization rules:

Let’s say we have the following schema:
```
type Post @model @auth(rules: [{allow: owner}]) {
  id: ID!
  content: String!
  owner: String!
  updatedAt: AWSDateTime!
}
```
And the following records in the DynamoDB table for this model

| id    | content | owner | updatedAt |
| ----- | ------- | ----- | --------- |
| A1 | Post 1 | alice | 2023-01-03T01:01:01.001Z |
| B2 | Post 2 | bob | 2023-02-02T01:01:01.001Z |
| C3 | Post 3 | bob | 2023-03-01T01:01:01.001Z |
| D4 | Post 4 | alice | 2023-04-13T01:01:01.001Z |
If we are logged in as the user Alice, DataStore will only have access to the records with ids “A1” and “D4”. The authorization logic for this is generated into the request mapping templates by the Amplify CLI and is enforced in the back end.

​If say we wanted to retrieve a subset of this data, for example, just the records that were created in the last week. We can specify a sync expression like:
```
DataStoreSyncExpression.syncExpression(Post.schema) {
  Post.keys.updatedAt.gt("2023-04-06")
}
```
Now, DataStore will only retrieve the record with id “D4”. There is no sync expression the client could set that would allow Alice to access Bob’s records.

For example, if we were to set
```
DataStoreSyncExpression.syncExpression(Post.schema) {
  Post.keys.owner.eq("bob")
}
```
DataStore would get back an empty result set.

​We have updated our documentation to clarify how selective sync works with authorization rules. You can refer to our [documentation](https://docs.amplify.aws/lib/datastore/sync/q/platform/ios/) to find the updates.

​Please reach out to [AWS Support](https://console.aws.amazon.com/support) if you have questions.
