### ISSUE TITLE
Integration Tests Failing in CI

### ISSUE THREAD

**Issue by ameter** [aws-amplify/amplify-swift#1781]
### Describe the bug

A number of integration tests are currently failing in GitHub Actions.

### Steps To Reproduce

```swift
run integration tests workflow
```

### Expected behavior

tests should pass

### Amplify Framework Version

n/a

### Amplify Categories

Analytics

### Dependency manager

Cocoapods

### Swift version

n/a

### CLI version

n/a

### Xcode version

n/a

### Is this a regression?

No

### Device

n/a

### iOS Version

n/a

### Specific to simulators

no

**Comment by atierian** [comment]
### Failures per test in the last 11 runs
| Test | Failures |
|---|---|
| analytics-integration-test | 8 |
| api-integration-test | 1 |
| auth-integration-test | 2 |
| datastore-integration-test | 4 |
| geo-integration-test | 0 |
| predictions-integration-test | 1 |
| storage-integration-test | 4 |
| api-graphqliam-integration-test | 2 |
| api-graphqluserpool-integration-test | 5 |
| api-restiam-integration-test | 0 |
| api-restuserpool-integration-test | 1 |
| api-graphqllambda-integration-test | 1 |

The only test that hasn't failed in the past 11 runs is `geo-integration-test`.
I didn't include metrics on the various `datastore-x-integration-test` because they're skipped if `datastore-integration-test` fails.

**Comment by phantumcode** [comment]
Analytics integration tests updated and passing.

**Comment by harsh62** [comment]
The tests has been fixed as part of Amplify 2.0 release.
