### ISSUE TITLE
Can't build with Amplify 2.0.1 when targeting iOS 11

### ISSUE THREAD

**Issue by frankiesimon** [aws-amplify/amplify-swift#2519]
### Describe the bug

My project targets iOS 11, when trying to build with the latest package version 2.0.1 I'm getting these errors:

Compiling for iOS 11.0, but module 'AWSCognitoAuthPlugin' has a minimum deployment target of iOS 13.0
Compiling for iOS 11.0, but module 'AWSPinpointAnalyticsPlugin' has a minimum deployment target of iOS 13.0

Is the newest version no longer compatible with iOS 11? Is this documented somewhere? Any chance it can be changed?

### Steps To Reproduce

```swift
Try to build with Amplify 2.0.1 when targeting iOS 11.
```

### Expected behavior

Build sucessfully.

### Amplify Framework Version

2.0.1

### Amplify Categories

Analytics, Auth

### Dependency manager

Swift PM

### Swift version

5.6.1

### CLI version

10.0.0

### Xcode version

13.4.1 13F100

### Is this a regression?

Yes

### Regression additional context

Didn't have an issue with Amplify 1.28.1

### Device

iPhone 8 Simulator / real device

### iOS Version

iOS 11 (target)

### Specific to simulators

No

**Comment by atierian** [comment]
Thanks for your question.
Version support is documented in the [README](https://github.com/aws-amplify/amplify-swift#platform-support).

> Amplify supports iOS 13+ and macOS 10.15+. Support for watchOS and tvOS is coming in future releases.

This applies to Amplify for Swift v2.0.0 and higher. For context, v2 of the library has adopted several structured concurrency language features, both in public APIs and internally. Since these language features require iOS 13+, the library supporting below that version would be very difficult.

**Comment by frankiesimon** [comment]
Thank you for your reply. That's understandable.

Will it be possible to still get 1.x updates for issues? There were two issues affecting analytics in production environments that were fixed in the latest releases and it would be extremely helpful if these were ported to a 1.x release. (I saw there was at least one such release after 2.0.0).

The ones I specifically refer to are the fix to make sure offline recorded events are retried indefinitely and the fix to the quotas check that would erroneously delete random properties even in cases where PinPoint would have accepted the event.

**Comment by atierian** [comment]
There is no change to the support level for v1 of the 'Amplify Library for Swift'. We will make an announcement if that changes.

So yes, v1 will still get updates.

**Comment by frankiesimon** [comment]
I see. So I should keep track of the releases and eventually the relevant issues will be merged into a 1.28.3 version?

The ones I refer to are #2518 #2497 #2484

**Comment by ruisebas** [comment]
@frankiesimon the issues you're referring to have been fixed in both v1 and v2:

- For v2.x, in release [**2.0.1**](https://github.com/aws-amplify/amplify-swift/releases/tag/v2.0.1)
- For v1.x, starting from release **1.28.1**. The fix was included in **AWS SDK for iOS** [2.28.1](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.28.1), so just update your dependencies and validate that you get this version. 

The changes from https://github.com/aws-amplify/amplify-swift/pull/2518 will indeed be included in the next v1 release, but they are not required to fix the actual issues you mentioned. They are addressing some discrepancies between v1 and v2 regarding error reporting to the `Hub`.

**Comment by frankiesimon** [comment]
@ruisebas I am not sure I understand. I had reported the original issue when I already was on 1.28.1:
|https://github.com/aws-amplify/amplify-swift/issues/2471

1.28.1 came out in September 15th and the release mentions
"Update AWS iOS SDK dependency to v2.28.0"

Since then 1.28.2 came out but I don't see a mention of bumping the AWS iOS SDK dependency for it. The Podfile.lock for 1.28.2 still points at the same AWS SDK:
https://github.com/aws-amplify/amplify-swift/blob/v1.28.2/Podfile.lock (If that's the right way to look at it).

**Comment by frankiesimon** [comment]
I can try that, thank you.

**Comment by frankiesimon** [comment]
Thank you - it looks like that updating in this way gets me the correct AWS SDK version.

**Comment by ruisebas** [comment]
@frankiesimon 
https://github.com/aws-amplify/amplify-swift/pull/2497 includes the quotas and connectivity fixes, but it only applies for **v2** (the `main` branch is Amplify v2, Amplify v1 code is now in the `v1` branch).

For **v1**, both of those issues are directly addressed in AWS SDK for iOS.
