### ISSUE TITLE
@hasOne relationship does not populate on SWIFT object with Datastore

### ISSUE THREAD

**Issue by traxes9k** [aws-amplify/amplify-swift#2611]
### Describe the bug

When pulling an object with a @hasOne attribute from datastore the object's property does not get populated. The @hasOne ID does get populated .

Following 'Steps To Reproduce' I get the below objects(see screenshot). Also attaching the CSV containing the data from Amplify studio .
[selected_12-14-2022.csv](https://github.com/aws-amplify/amplify-swift/files/10222728/selected_12-14-2022.csv)
![Screenshot 2022-12-14 at 00 54 47](https://user-images.githubusercontent.com/69757418/207462675-f7442dae-ace4-4e48-8b19-e7e7858ceaf5.png)

### Steps To Reproduce

```swift
1.Create GraphQL api with the schema from Amplify Studio
type Expert @model @auth(rules: [{allow: public, operations: [create, read, update]}]) {
  id: ID!
  name: String!
  bio: String!
  experieceYears: Int!
  expertCategory: Categories @hasOne
  picture_file: String
  cv_fil: String
}

type Categories @model @auth(rules: [{allow: public, operations: [read]}]) {
  id: ID!
  name: String!
  description: String!
  tags: [String!]
  image: String!
}

2.Add some data
3.Pull all the Expert instances in iOS from Datastore with the bellow function  

static func getExperts(onExperts:([Expert]) -> Void) async
    {
        
        do {
            let items = try await Amplify.DataStore.query(Expert.self)
            onExperts(items)
        } catch let error as DataStoreError {
            print("Error querying items: \(error)")
        } catch {
            print("Unexpected error: \(error)")
        }
        
    }
```

### Expected behavior

Based on steps to reproduce the [EXPERT_OBJECT].expertCategory field should contain a category .

### Amplify Framework Version

2.2.0

### Amplify Categories

DataStore

### Dependency manager

Swift PM

### Swift version

5.7

### CLI version

10.5.2

### Xcode version

14.1

### Is this a regression?

No

### Device

iPhone 14 Pro

### iOS Version

16.1

### Specific to simulators

NO

**Comment by thisisabhash** [comment]
Hello, Thank you for posting this. This issue has recently been fixed with the latest CLI release and Lazy Loading feature. 
Please follow steps here : https://docs.amplify.aws/cli/migration/lazy-load-custom-selection-set/#datastore-swift-bi-directional-has-one-relationship-support
Your `amplify -v` should output `11.0.3` and your Amplify Swift version should be 2.6.0 onwards.
After making these changes, you will see a `LazyReference` to the `Expert.Categories` field as below.

<img width="624" alt="Screenshot 2023-03-24 at 2 51 25 PM" src="https://user-images.githubusercontent.com/23294582/227648955-8478b4e4-8426-4e73-be60-e5ebd5442d0e.png">

This can be accessed as following method:

```
func getExperts() async {
        do {
            let items = try await Amplify.DataStore.query(Expert.self)
            let expert = items[0]
            let expertCategory: Categories? = try await expert.expertCategory
            print("Category: \(String(describing: expertCategory?.name))")
            print("Queried items: \(items)")
        } catch let error as DataStoreError {
            print("Error querying items: \(error)")
        } catch {
            print("Unexpected error: \(error)")
        }  
    }
```
