### ISSUE TITLE
Url Request headers not being passed

### ISSUE THREAD

**Issue by xxjt123xx** [aws-amplify/amplify-swift#2678]
### Describe the bug

When we add url request headers these are not being sent with the request to appsync. e.g. sending of user agent or custom headers.

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Add urlinterceptor
2. No headers are being sent when using the datastore
```

### Expected behavior

Request headers to be applied to the request

### Amplify Framework Version

1.28.4

### Amplify Categories

API, DataStore

### Dependency manager

Swift PM

### Swift version

5.7.2

### CLI version

10.6.0

### Xcode version

14.2

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


INSERT LOG MESSAGES HERE
```
</details>
```


### Is this a regression?

No

### Regression additional context

_No response_

### Device

iphone 14

### iOS Version

16.2

### Specific to simulators

no

### Additional context

_No response_

**Comment by lawmicha** [comment]
I believe this is one part bug, and one part feature request. The issue is that User-Agent isn't being passed on subscription requests, which causes subscriptions to fail for certain backend configurations. We have a fix for that here: https://github.com/aws-amplify/amplify-swift/pull/2700

The feature request is 

> When we add url request headers these are not being sent with the [subscription] request to appsync. e.g. sending of user agent or custom headers

As I understand, the fix should render it unnecessary for the customer to intercept the request. Can you provide some addition details for the feature request such as what custom headers you are providing and why they are necessary? The library will intercept the request with default interceptors built-in and add the User-Agent (once we release the fix). Based on the details, it will help drive the design of the library changes we can do, and understand whether this is just a change on the library or both the library and something required from the AppSync service.

**Comment by lawmicha** [comment]
The fix was released https://github.com/aws-amplify/amplify-swift/pull/2700. Please reopen if the second part about the feature request is still relevant, and any more details on the questions above.
