### ISSUE TITLE
After Changing Schema: No Cloud Syncing and "The key `__typename` was not found" Error

### ISSUE THREAD

**Issue by julianworden** [aws-amplify/amplify-swift#2858]
### Describe the bug

This may be related to #507.

I have a type called Session, and it used to look like this in my graphql schema:

```
type Session @model @auth(rules: [{allow: public}]) {
  id: ID!
  project: Project @belongsTo
  durationInSeconds: Int!
  unixDate: Float!
}
```

Everything was working fine. I could perform CRUD operations and all changes would sync with the Cloud. Then, I wanted to add a weekday property to the Session type, so I created a Weekday enum, added a weekday property to Session, did `amplify codegen models`, did `amplify push`, and now my schema looks like this including all my other types:

```
type User @model @auth(rules: [{allow: public}]) {
  id: ID!
  username: String!
  externalProvider: ExternalProvider
  projects: [Project] @hasMany
}

type Project @model @auth(rules: [{allow: public}]) {
  id: ID!
  creator: User @belongsTo
  name: String!
  priority: Priority!
  description: String
  sessions: [Session] @hasMany
}

type Session @model @auth(rules: [{allow: public}]) {
  id: ID!
  project: Project @belongsTo
  durationInSeconds: Int!
  unixDate: Float!
  weekday: Weekday!
}

enum Priority {
  low
  normal
  high
}

enum ExternalProvider {
  google
  apple
}

enum Weekday {
  sunday
  monday
  tuesday
  wednesday
  thursday
  friday
  saturday
}
```

Now, no new data is synced with the Cloud at all. Sessions, Users, and Projects are saved locally without issue, but no new Sessions, Users, or Projects get saved to the Cloud. Furthermore, in the Content tab of Amplify Studio I see this error message when I go to the Session table (this error only appears for the Session table, the Project and User tables look normal):

<img width="1192" alt="Screenshot 2023-04-09 at 9 12 32 AM" src="https://user-images.githubusercontent.com/93101937/230783917-ab65e113-cb7a-419b-b928-46c9e88bbb43.png">

To me, this error message signifies that I still have Session data stored locally that does not include this mandatory weekday property. This would make perfect sense since it would mean I would be trying to sync invalid Sessions with the Cloud. To test this, I reverted my schema back to the way it was before I added the weekday property, did `amplify codegen models`, did `amplify push`, and performed the following operation to fetch all Sessions and delete them in an effort to have no sessions of any kind left on my device:

```
let sessions = try? await Amplify.DataStore.query(Session.self)
for session in session {
    try? await Amplify.DataStore.delete(session)
}
```

This worked, all of my Sessions were deleted both locally and in the cloud (I know this is true because I printed the result of `try? await Amplify.DataStore.query(Session.self)` after running the above delete operation and it was an empty array. There were also no Sessions shown in Amplify Studio), and all User, Project, and Session data was being synced as expected.

So, I once again changed my schema back to the version listed above that includes the mandatory weekday property, did `amplify codegen models`, and did `amplify push` and I get the same "Failed to retrieve 44 record(s)" error in Amplify Studio again. I also get these errors printed in the Xcode console every time I use `Amplify.DataStore` to do anything that has to do with a Session (queries, CRUD operations, etc.): 

```
2023-04-09 08:14:25.676266-0700 Accountable[45495:11163593] [AWSDataStorePlugin] StorageEngine completed with error: DataStoreError: One or more errors occurred syncing models. See below for detailed error description.
Recovery suggestion: DataStoreError: An error occurred syncing Session
Caused by:
DataStoreError: failed to process graphqlResponseData
Caused by:
APIError: failed to process graphqlResponseData
Caused by:
DataStoreError: The key `__typename` was not found
Recovery suggestion: Check if the parsed JSON contains the expected `__typename`
Caused by:
DataStoreError: One or more errors occurred syncing models. See below for detailed error description.
Recovery suggestion: DataStoreError: An error occurred syncing Session
```

Not only do I not understand why no new data is syncing with the cloud, but I also don't understand where these "44 record(s)" are coming from. Currently, there are no Sessions of any kind being stored locally and there are no Sessions being stored in the Cloud, yet this number never changes. So far, I've tried:

- Everything listed above
- Disabling conflict detection and re-enabling it (I'm using auto merge conflict detection). I did this with `amplify update api`, disable conflict detection, `amplify push`, `amplify update api`, enable auto merge conflict detection
- `try await Amplify.DataStore.clear()` to hopefully remove all local data from the device
- Save and Deploy from the Data tab of Amplify Studio, and then `amplify pull`

The need to update a schema seems like it'd be incredibly common and I don't see anybody else reporting this issue, so what is the correct workflow here?

### Workarounds

I've found 2 workarounds for this issue, but both of them are far from ideal:

- Make the weekday property optional. This isn't ideal because every Session needs a weekday property for certain functionality in my app, so making the property optional would make some of my code error prone
- Remove the Session type from my schema altogether, do an `amplify codegen models`, do an `amplify push`, add the Session type back into my schema, do an `amplify codegen models`, and then do an `amplify push`. This is a better workaround, but it just seems clunky and error prone for live apps that have lots of users. Also, I don't see this workflow documented anywhere, which is leading me to think it's not how updating a schema is supposed to work.

### Steps To Reproduce

Steps are outlined in my description of the bug above.

### Expected behavior

Syncing between local data and cloud data should continuously work after changing the schema.

### Amplify Framework Version

2.8.0

### Amplify Categories

API, DataStore

### Dependency manager

Swift PM

### Swift version

5.7

### CLI version

11.0.3

### Xcode version

14.2

### Is this a regression?

No

### Device

iPhone 14 Pro Simulator

### iOS Version

iOS 16.2

### Specific to simulators

No

### Additional context

I'm posting my Amplify setup code that I have in my `@main` file here in case it's helpful:

```
init() {
        configureAmplify()
}

func configureAmplify() {
    let apiPlugin = AWSAPIPlugin()
    let dataStorePlugin = AWSDataStorePlugin(modelRegistration: AmplifyModels())

    do {
        SDKLoggingSystem.initialize(logLevel: .warning)
        try Amplify.add(plugin: apiPlugin)
        try Amplify.add(plugin: dataStorePlugin)
        try Amplify.add(plugin: AWSCognitoAuthPlugin())
        try Amplify.configure()
        Task {
            try await Amplify.DataStore.start()
        }
        print("Initialized Amplify")
    } catch {
        print("Could not initialize Amplify: \(error)")
    }
}
```

**Comment by julianworden** [comment]
Sounds great, thanks!

**Comment by BrandowBuenos** [comment]
Same error here. I'm using amplify in flutter and yesterday and today I had this problem with users in production. How can I resolve this error?

**Comment by royjit** [comment]
@julianworden I was able to reproduce your issue. As per my research here is my findings: The initial sync when the Datastore starts try to sync all the models from the backend. Since some of the items in your backend DDB does not have required fields, they will not get synced resulting in SyncEngine in Datastore not to start. So this will fail adding new items as well to backend. 

One work around I could see if backfilling the existing items in the backend with the required field. Let me know if that works for you.

**Comment by BrandowBuenos** [comment]
Update for everyone experiencing the same issue: despite giving the impression that it is a datastore error, this message is generic and can indicate other types of errors. In my case, there were data relationship errors where the ID of another entity was null even though it shouldn't be. I was able to resolve this by fixing these problematic relationships.

To identify these errors, make the calls directly in the application's GRAPHQL playground. Items with errors will appear at the end of the JSON, inside the "errors" object.

I hope this helps!

**Comment by frnzgmbh** [comment]
Error:
DataStoreError: The key __typename was not found

General root cause:
There is an inconsistency with database/tables/items/entry value. This means that you have an entry that does not match your defined schema structure, or the database on the cloud is in contradict with the database on the device.

Solution:
You need to find that particular non-conforming table, or item, or entry value and amend/delete that from database on the cloud. Restart, and you are good to go.

**Comment by fzy-spyro** [comment]
I believe there is another layer to this issue. In case this `__typename` error is logged by Amplify, Error handler is not called. See eg. issue: https://github.com/aws-amplify/amplify-swift/issues/3028 

IMO It would be good if Amplify called that error handler in such cases so your app can react propery becasue right now it is more like a silent error that can easily go unnoticed.

**Comment by lawmicha** [comment]
>  `weekday: Weekday!` -> `weekday: Weekday`

For upgrading schema scenarios, it's best to make the new fields optional instead of required so that when data is being synced with DataStore, the data missing the new field values can be decoded to the new codegen model types containing the new optional property. This is especially important when the app has already gone into production and as @royjit  mentioned, during development, backfilling required fields in DynamoDB table will fix the syncing issues.

> DataStoreError: The key __typename was not found

We'll have to reproduce the required field upgrade scenario to see how it's making it to this error message, and possibly branch off to make a more verbose debug message

**Comment by marcusmcintyre** [comment]
I can confirm with @lawmicha that in order to resolve this, you can (should) make the new field optional.

I have been experiencing the same error message and was curious how to handle it appropriately.

For new apps you could clear all the existing data but for existing apps this is the preferred way to handle it. It makes sense if you think about it. You're trying to decode these objects but they don't have the required field so it throws an error.

The last option is to backfill the database as others have suggested, but keeping the field optional should satisfy most requirements.
