### ISSUE TITLE
Apple privacy manifest

### ISSUE THREAD

**Issue by AntonyARHS** [aws-amplify/amplify-swift#3449]
Hi, 

I would like to ask a question regarding the new permission file from Apple: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

As we don't know what APIs are used internally in your library, could you confirm whether or not you will be managing the new permission file required by Apple? If you have to handle it, do you have an ETA?

Thank you very much,

**Comment by ruisebas** [comment]
Hi @AntonyARHS, privacy manifests describing the usage of **required reason APIs** were added to our libraries in [2.21.5](https://github.com/aws-amplify/amplify-swift/releases/tag/2.21.5).

We also have [an issue tracking adding **data collection**](https://github.com/aws-amplify/amplify-swift/issues/3326), but since this hasn't been required by Apple we don't have an ETA yet.

Closing.
