### ISSUE TITLE
Unable to add Package dependencies of Xcode(IOS)

### ISSUE THREAD

**Issue by Wilsonagene** [aws-amplify/amplify-swift#3907]
### Describe the bug

I am unable to add the Package dependencies for IOS Xcode 
 Errors are in the image below:

<img width="1139" alt="Screenshot 2024-10-28 at 4 52 09 PM" src="https://github.com/user-attachments/assets/ddc1e637-7973-4004-ac39-ae4393d43d02">
<img width="1171" alt="Screenshot 2024-10-28 at 4 52 27 PM" src="https://github.com/user-attachments/assets/e8025e39-ecf1-4c07-9fb8-c227cba37ddc">

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Go to Package dependencies on Xcode
2. Paste the link of "https://github.com/aws-amplify/amplify-swift"
3. Click on Add package
4. See error
```

### Expected behavior

After clicking on Add package the package should be added to your Xcode project

### Amplify Framework Version

4.43.0

### Amplify Categories

Analytics, API, Auth, DataStore, Geo, Predictions, Storage

### Dependency manager

Swift PM

### Swift version

5.0

### CLI version

12.1.1

### Xcode version

15.4

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


INSERT LOG MESSAGES HERE
```
</details>
```


### Is this a regression?

No

### Regression additional context

_No response_

### Platforms

iOS

### OS Version

17.5

### Device

iPhone 15

### Specific to simulators

_No response_

### Additional context

_No response_

**Comment by ruisebas** [comment]
Hi @Wilsonagene. 
I was unable to reproduce the issue and was able to add Amplify Swift to an Xcode project by following the steps you provided.

It's not possible to see the full error in the screenshots you provided, but it seems the issue seems when attempting to load the `aws-sdk-swift` package.
Have you tried doing **File > Packages > Reset Package Caches**?

**Comment by Wilsonagene** [comment]
It's  the normal process of adding package to Xcode.

I am unable to try File > Packages > Reset Package Caches?

<img width="576" alt="Screenshot 2024-10-28 at 5 54 45 PM" src="https://github.com/user-attachments/assets/e8832a46-fe62-49e6-9543-f6d26372750f">

**Comment by ruisebas** [comment]
I see, I guess the options are greyed out because you don't have any package in that specific project.

This seems to be a network issue when Xcode tried to fetch the package, but not something caused by the package itself. 
Are you perhaps behind a VPN or proxy you need to configure?

If that's not the case, you could try removing the affected packages from the list of "Recently Used" in Xcode by right-clicking and choosing "Remove Package", or just try wiping the whole SPM caches directory altogether:

```bash
rm -rf ~/Library/Caches/org.swift.swiftpm/
```

In any case, this issue is not something we have control of.

**Comment by kparichan** [comment]
Might be related to this if you use SourceTree.
https://forums.swift.org/t/fatal-cannot-use-bare-repository/75588

**Comment by Wilsonagene** [comment]
no it's not sourceTree I have checked

**Comment by ruisebas** [comment]
I can't reproduce this issue in either Xcode 15.4 nor Xcode 16, so I don't think it's related to that.
But feel free to give it a shot.

**Comment by Wilsonagene** [comment]
> I can't reproduce this issue in either Xcode 15.4 nor Xcode 16, so I don't think it's related to that. But feel free to give it a shot.

But I try other packages  and it worked

**Comment by Wilsonagene** [comment]
I my Derived Data folder and I was able to add the package to my project
