### ISSUE TITLE
Listen in to a custom subscription within an AppSync schema

### ISSUE THREAD

**Issue by benrosen78** [aws-amplify/amplify-swift#661]
**Is your feature request related to a problem? Please describe.**
Amplify for iOS currently does not seem to have the capability to create a subscription for a change besides the default Subscription handler for a Model object. What I would like is to be able to pass in inputs to filter my subscription by ID or by some other parameter.

This is the subscription I currently have set up in my schema. As you can see, it takes an ID as a parameter.
```graphql
type Subscription {
	onUpdate(id: ID!): Item
		@aws_subscribe(mutations: ["updateItem"])
}
```

**Describe the solution you'd like**
I would like a way to specify the name of a subscription function and pass parameters into it before listening to it. I would like to see it as an optional parameter in the `subscription` `enum` for `GraphQLRequest`. 

For what it's worth, I was able to find a work-around to accomplish this. 
```swift
let request = GraphQLRequest(apiName: "myapi", document: "subscription { onUpdate(id: \"19dee48e-6daa-417d-a9b1-8d7108ab8735\") { id, conversionCount } }", variables: [:], responseType: JSONValue.self, decodePath: nil)
subscription = Amplify.API.subscribe(request: .subs, valueListener: { _ in
    // do stuff
}, completionListener: nil)
```

**Comment by lawmicha** [comment]
Hi @benrosen78, thanks for the detailed solution. The Model types generated from `amplify codegen models` uses the graphql schema with types containing the `model` directive, which is also used in the GraphQL Transform to generate the 
AppSync API and related [resources](https://docs.amplify.aws/cli/graphql-transformer/directives#generates). The [extensions](https://github.com/aws-amplify/amplify-ios/blob/main/AmplifyPlugins/Core/AWSPluginsCore/Model/GraphQLRequest/GraphQLRequest+Model.swift#L189) help build the GraphQLRequest for those APIs and do not currently take in optional inputs since there wasn't a clear requirement for it. 

To identify the need for it, how did you provision the AppSync service? Through AppSync console? or was there a set of directives that you used that provisioned the subscription API with`id` as input?

The work-around is what we would expect for requests which need customization. You can also extract the variable out to dynamically inject it. 

```
let variables = ["id": id] // `id` variable
let request = GraphQLRequest(apiName: "myapi", document: "subscription($id: ID!) { onUpdate(id: $id) { id, conversionCount } }", variables: variables, responseType: JSONValue.self, decodePath: nil)
subscription = Amplify.API.subscribe(request: .subs, valueListener: { _ in
    // do stuff
}, completionListener: nil)
```
[Another example here](https://github.com/aws-amplify/amplify-ios/issues/599#issuecomment-658382676)

Also, is there a reason to use `JSONValue` as the response type over the Model type or a Codable type that matches your `Item` type?

**Comment by LaszloDev** [comment]
Your own docs specify the way to create custom subscriptions with arguments. Still this is categorised as iOS, the example code is in JavaScript:
https://docs.amplify.aws/guides/api-graphql/subscriptions-by-id/q/platform/ios

Also adding the mentioned `Subscription` does only have the effect with `amplify codegen models` that two more files are created (`Subscription.swift` & `Subscription+Schema.swift`) which are basically empty
```
// swiftlint:disable all
import Amplify
import Foundation
```

We have multiple clients needed to subscribe to updates of their own data. In the moment every client gets every update and is missing a separation, so a default support would be greatly appreciated..

**Comment by leungy2** [comment]
I am encountering the same problem, and when I use the workaround I get a "Failed to decode GraphQL response to the 'ResponseType' Item
Any help would be appreciated!

**Comment by thisisabhash** [comment]
@[LaszloDev](https://github.com/LaszloDev) Could you please open a new issue with details you mentioned in your comments?

**Comment by lawmicha** [comment]
Please track https://github.com/aws-amplify/docs/pull/5649 for the Upgrade Guide. Once we have this ready, the latest CLI will allow generating API.swift through `amplify codegen types` that is compatible with Amplify.API, thus custom subscriptions use case like this will be possible
