### ISSUE TITLE
Amplify DataStore configuration does not allow which apiName to specify if multiple APIs are configured.

### ISSUE THREAD

**Issue by johnm555** [aws-amplify/amplify-swift#848]
It seems the dataStore configuration does not allow which apiName to specify if multiple APIs are configured.

_Originally posted by @johnm555 in https://github.com/aws-amplify/amplify-ios/issues/814#issuecomment-713161491_

**Comment by lawmicha** [comment]
DataStore will use the first GraphQL API configured in the configuration, so if you have multiple GraphQL APIs, it won't know which one to use, since there's no way to configure the "apiName" from DataStore. Are you still blocked on setting up your Amplify dependencies? This is very similar to other issues such as having DataStore and API in the same app. I'm looking to consolidate this feature request in one issue over in https://github.com/aws-amplify/amplify-swift/issues/739 Please track this and provide your input. Thanks!
